# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debc40b843d976ccf99942af52f94dc7df034cb332c192da2bc990f83db8c01f4fab69988d7241dca5a338056d93810a99f96369e15d5bc99a52a97abeb81eac

test:
  secret_key_base: 7cd879ade4f933bd63fd81afa0f0ab12b3079ddfe889c2ac09c7c334e265d86be5ccca9844ab6d46236f943847e33f2e5b89a08bf1c3047db825f508c98a2dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
